# Tensors

In [2]:
from __future__ import print_function
import torch

## 1.构造一个未初始化的5x3矩阵：

In [3]:
x = torch.empty(5, 3)

print(x)

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.7245e-39, 1.0286e-38, 9.0919e-39],
        [9.0919e-39, 9.2755e-39, 8.7245e-39]])


## 2.构造一个随机初始化的矩阵

In [4]:
x = torch.rand(5, 3)

print(x)

tensor([[0.4970, 0.3256, 0.9993],
        [0.6548, 0.3759, 0.5497],
        [0.2385, 0.2329, 0.0086],
        [0.5942, 0.4321, 0.6232],
        [0.7486, 0.7339, 0.6331]])


## 3.构造一个填充零且dtype为long的矩阵：

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)

print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 4.直接从数据构造张量

In [6]:
x = torch.tensor([5.5, 3])

print(x)

tensor([5.5000, 3.0000])


## 5.基于现有张量创建张量

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)

print(x)

x = torch.randn_like(x, dtype=torch.float)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.2812, -1.1538,  0.5630],
        [ 1.1862,  2.0615,  0.4064],
        [ 0.2490, -0.6191, -1.5156],
        [-0.1165, -0.3954,  0.1742],
        [-3.3473,  1.6671,  0.1250]])


## 6.得到x的形状

In [8]:
print(x.size())

torch.Size([5, 3])


## 7.加法-语法1

In [9]:
y = torch.rand(5, 3)

print(x + y)

tensor([[-1.2940, -0.2051,  1.5352],
        [ 2.0997,  3.0501,  0.7871],
        [ 1.1093, -0.5799, -1.3014],
        [ 0.6430,  0.0894,  0.5216],
        [-2.7034,  1.8093,  0.9353]])


## 8.加法-语法2

In [10]:
print(torch.add(x, y))

tensor([[-1.2940, -0.2051,  1.5352],
        [ 2.0997,  3.0501,  0.7871],
        [ 1.1093, -0.5799, -1.3014],
        [ 0.6430,  0.0894,  0.5216],
        [-2.7034,  1.8093,  0.9353]])


## 9.加法:提供输出张量作为参数

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.2940, -0.2051,  1.5352],
        [ 2.0997,  3.0501,  0.7871],
        [ 1.1093, -0.5799, -1.3014],
        [ 0.6430,  0.0894,  0.5216],
        [-2.7034,  1.8093,  0.9353]])


## 10.加法到位

In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.2940, -0.2051,  1.5352],
        [ 2.0997,  3.0501,  0.7871],
        [ 1.1093, -0.5799, -1.3014],
        [ 0.6430,  0.0894,  0.5216],
        [-2.7034,  1.8093,  0.9353]])


## 11.调整张量的大小

In [13]:
x = torch.randn(4, 4)

y = x.view(16)

z = x.view(-1, 8)

print(x.size(), y.size(),z.size())

print(x)

print(y)

print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.3357,  0.7243, -1.0664,  0.0058],
        [ 0.8511, -0.7215,  1.1949, -0.2666],
        [ 0.1071, -0.1617,  0.7237, -0.4714],
        [-0.5255,  0.8697, -0.2822, -2.9163]])
tensor([ 1.3357,  0.7243, -1.0664,  0.0058,  0.8511, -0.7215,  1.1949, -0.2666,
         0.1071, -0.1617,  0.7237, -0.4714, -0.5255,  0.8697, -0.2822, -2.9163])
tensor([[ 1.3357,  0.7243, -1.0664,  0.0058,  0.8511, -0.7215,  1.1949, -0.2666],
        [ 0.1071, -0.1617,  0.7237, -0.4714, -0.5255,  0.8697, -0.2822, -2.9163]])


## 12.item()获取张量的数值

In [14]:
x = torch.randn(1)

print(x)

print(x.item())

tensor([-0.0415])
-0.041493531316518784


## 13.将torch的tensor转化为numpy的array

In [15]:
a = torch.ones(5)

print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()

print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)

print(a)

print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 14.将numpy的array转化为torch的tensor

In [18]:
import numpy as np

a = np.ones(5)

b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a)

print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 15.CUDA Tensors

In [19]:
if torch.cuda.is_available():
    
    device = torch.device("cuda")
    
    y = torch.ones_like(x, device=device)
    
    x = x.to(device)
    
    z = x + y
    print(z)
    
    print(z.to("cpu", torch.double))

tensor([0.9585], device='cuda:0')
tensor([0.9585], dtype=torch.float64)


# AUTOGRAD: AUTOMATIC DIFFERENTIATION

## 16.创建一个张量并设置require_grad = True来跟踪它的计算

In [20]:
x = torch.ones(2, 2, requires_grad=True)

print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y = x + 2

print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(y.grad_fn)

In [23]:
z = y * y * 3

out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [24]:
a = torch.randn(2, 2)

a = ((a * 3) / (a - 1))

print(a.requires_grad)

a.requires_grad_(True)

print(a.requires_grad)

b = (a * a).sum()

print(b.grad_fn)

False
True


In [25]:
out.backward()

In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
